services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tickdb-producer
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - tickdb-net

networks:
  tickdb-net:
    external: true