services:
  jupyter:
    image: jupyter/pyspark-notebook:latest
    container_name: tickdb-jupyter
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=tickdb
    volumes:
      - ./notebook:/home/jovyan/work
    networks:
      - tickdb-net

networks:
  tickdb-net:
    external: true